CREATE TABLE TableCost (Id SMALLINT NOT NULL DEFAULT 0
,RheumCount SMALLINT NULL DEFAULT 0
, CoughCount SMALLINT NULL DEFAULT 0
, ASoreThroatCount SMALLINT NULL DEFAULT 0
, FeverTemperatureCount SMALLINT NULL DEFAULT 0
, JointPainCount SMALLINT NULL DEFAULT 0
, SoreThroatCount SMALLINT NULL DEFAULT 0
, SputumCount SMALLINT NULL DEFAULT 0
, RattlingInLungsCount SMALLINT NULL DEFAULT 0
, vomitingCountCount SMALLINT NULL DEFAULT 0
, ASoreThroatPain SMALLINT NULL DEFAULT 0
, PainInLungsCount SMALLINT NULL DEFAULT 0
, NotSayCount SMALLINT NULL DEFAULT 0)