//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB_II_1.Local {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LB_II_1.Local.Local_RU", typeof(Local_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ангина.
        /// </summary>
        internal static string Ang {
            get {
                return ResourceManager.GetString("Ang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Боль в горле.
        /// </summary>
        internal static string ASoreThroatPain {
            get {
                return ResourceManager.GetString("ASoreThroatPain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бронхит.
        /// </summary>
        internal static string Bro {
            get {
                return ResourceManager.GetString("Bro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кашель.
        /// </summary>
        internal static string Cough {
            get {
                return ResourceManager.GetString("Cough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диагностика.
        /// </summary>
        internal static string Diagnostic_button_name {
            get {
                return ResourceManager.GetString("Diagnostic_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жар.
        /// </summary>
        internal static string FeverTemperature {
            get {
                return ResourceManager.GetString("FeverTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грипп.
        /// </summary>
        internal static string Flu {
            get {
                return ResourceManager.GetString("Flu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить.
        /// </summary>
        internal static string GET_B {
            get {
                return ResourceManager.GetString("GET_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Боль в суставах.
        /// </summary>
        internal static string JointPain {
            get {
                return ResourceManager.GetString("JointPain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ENG.
        /// </summary>
        internal static string Local_button_name {
            get {
                return ResourceManager.GetString("Local_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Потеря голоса.
        /// </summary>
        internal static string NotSay {
            get {
                return ResourceManager.GetString("NotSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Боль в легких.
        /// </summary>
        internal static string PainInLungs {
            get {
                return ResourceManager.GetString("PainInLungs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фарингит.
        /// </summary>
        internal static string Pha {
            get {
                return ResourceManager.GetString("Pha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пневмония.
        /// </summary>
        internal static string Pne {
            get {
                return ResourceManager.GetString("Pne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DAI.
        /// </summary>
        internal static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diagnostic Artificial Intelligence.
        /// </summary>
        internal static string ProgNameFull {
            get {
                return ResourceManager.GetString("ProgNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хрип в легких.
        /// </summary>
        internal static string RattlingInLungs {
            get {
                return ResourceManager.GetString("RattlingInLungs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насморк.
        /// </summary>
        internal static string Rheum {
            get {
                return ResourceManager.GetString("Rheum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных.
        /// </summary>
        internal static string SeenDB_button_name {
            get {
                return ResourceManager.GetString("SeenDB_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SET_B {
            get {
                return ResourceManager.GetString("SET_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспаление горла.
        /// </summary>
        internal static string SoreThroat {
            get {
                return ResourceManager.GetString("SoreThroat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макрота.
        /// </summary>
        internal static string Sputum {
            get {
                return ResourceManager.GetString("Sputum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уст. балы симптомов.
        /// </summary>
        internal static string SymCostSet_button_name {
            get {
                return ResourceManager.GetString("SymCostSet_button_name", resourceCulture);
            }
        }
    }
}
